version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  frontend:
    container_name: frontend
    build: frontend
    image: "node:14-alpine"
    user: "node"
    working_dir: /erabnb
    volumes:
      - ./frontend:/erabnb/frontend
    command: "npm start"
    depends_on:
      - backend

  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:reset && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/erabnb
    ports:
      - "3000:3000"
    depends_on:
      - db
